version: '3.7'

services:
    api:
        build:
            context: ./app 
            dockerfile: Dockerfile.prod
        command: gunicorn api.wsgi:application --bind 0.0.0.0:9000
        volumes:
            - static_volume:/home/app/api/staticfiles
            - media_volume:/home/app/api/mediafiles
        expose:
            - 9000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db 

    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/api/staticfiles
            - media_volume:/home/app/api/mediafiles
        ports:
            - 9000:80
        depends_on:
            - api

volumes:
    postgres_data:
    static_volume:
    media_volume:
